// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    created_at,
    updated_at,
    user_id,
    email)
VALUES (
    gen_random_uuid (),
    NOW(),
    NOW(),
    $1,
    $2)
RETURNING
    id, create_at, update_at, user_id, email
`

type CreateUserParams struct {
	UserID string
	Email  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreateAt,
		&i.UpdateAt,
		&i.UserID,
		&i.Email,
	)
	return i, err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT
    id, create_at, update_at, user_id, email
FROM
    users
WHERE
    user_id = $1
`

func (q *Queries) GetUserInfo(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserInfo, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreateAt,
		&i.UpdateAt,
		&i.UserID,
		&i.Email,
	)
	return i, err
}
