// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: animes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAnimes = `-- name: GetAnimes :one
SELECT
    animes_id, created_at, updated_at, title
FROM
    animes
WHERE
    animes_id = $1
`

func (q *Queries) GetAnimes(ctx context.Context, animesID uuid.UUID) (Anime, error) {
	row := q.db.QueryRowContext(ctx, getAnimes, animesID)
	var i Anime
	err := row.Scan(
		&i.AnimesID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}
