// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id,
    token,
    created_at,
    updated_at,
    expires_at,
    revoked_at)
VALUES (
    $1,
    $2,
    NOW(),
    NOW(),
    NOW() + interval '60 days',
    $3)
RETURNING
    id, token, created_at, updated_at, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	Token     string
	RevokedAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.ID, arg.Token, arg.RevokedAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
