// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID       uuid.UUID
	CreateAt time.Time
	UpdateAt time.Time
	UserID   string
	Email    string
}
