// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Anime struct {
	AnimesID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
}

type RefreshToken struct {
	ID        uuid.UUID
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Review struct {
	ReviewID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Star      int32
	Body      sql.NullString
	UserID    uuid.UUID
	AnimesID  uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreateAt       time.Time
	UpdateAt       time.Time
	UserID         string
	Email          string
	HashedPassword string
}
