// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getReviews = `-- name: GetReviews :one
SELECT
    review_id, created_at, updated_at, star, body, user_id, animes_id
FROM
    reviews
WHERE
    review_id = $1
`

func (q *Queries) GetReviews(ctx context.Context, reviewID uuid.UUID) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviews, reviewID)
	var i Review
	err := row.Scan(
		&i.ReviewID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Star,
		&i.Body,
		&i.UserID,
		&i.AnimesID,
	)
	return i, err
}
